<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 Badge.glb -t
-->

<script lang="ts">
	import animation from './animation.json';
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { Theatre, Editable, Sheet } from '@threlte/theatre';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Badge_1: THREE.Mesh;
			Badge_2: THREE.Mesh;
			Badge_3: THREE.Mesh;
		};
		materials: {
			Rest: THREE.MeshStandardMaterial;
			Inner: THREE.MeshStandardMaterial;
			Ring: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/Badge.glb');

	const component = forwardEventHandlers();
</script>

<Theatre config={{ state: animation }}>
	<Sheet autoPlay>
		<Editable name="Badge" props={{ scale: 0, opacity: 0, rotation: 0 }} let:values>
			<T
				is={ref}
				dispose={false}
				{...$$restProps}
				scale={values.scale}
				rotation.y={values.rotation}
				bind:this={$component}
			>
				{#await gltf}
					<slot name="fallback" />
				{:then gltf}
					<T.Mesh
						geometry={gltf.nodes.Badge_1.geometry}
						material={gltf.materials.Rest}
						material.opacity={values.opacity}
						material.transparent
						material.side={0}
					/>
					<T.Mesh
						geometry={gltf.nodes.Badge_2.geometry}
						material={gltf.materials.Inner}
						material.opacity={values.opacity}
						material.transparent
						material.side={0}
					/>
					<T.Mesh
						geometry={gltf.nodes.Badge_3.geometry}
						material={gltf.materials.Ring}
						material.opacity={values.opacity}
						material.transparent
						material.side={0}
					/>
				{:catch error}
					<slot name="error" {error} />
				{/await}

				<slot {ref} />
			</T>
		</Editable>
	</Sheet>
</Theatre>
